# Generated by Django 6.0.3 on 2026-03-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='lista',
        ),
    ]
