# Generated by Django 6.0.3 on 2026-03-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lista', '0002_rename_tarefa_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='deletada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lista',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
